name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AI_CHEF_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.AI_CHEF_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean via SSH
        run: |
          ssh root@${{ secrets.AI_CHEF_HOST }} << 'EOF'
            cd /root/AI-Chef
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            EOF
